servername: main
eshost: localhost
esport: 9200
default-world: world
debug: false
new-player-message: "You have been successfully Indexed"
unsecured: true
ban-appeal-suffix: "You can appeal at https://foxelbox.com"