name: JawaPermissions
main: jawamaster.jawapermissions.JawaPermissions
version: ${pom.version}
description: "A permissions and player manegment plugin using the ElasticSearch Database."
author: Jawamaster (Arthur Bulin)
api-version: 1.20
commands:
  uuid:
    description: This command returns the UUID of a user.
    usage: /uuid [<player>]
    permission: jawapermissions.getuuid
  setrank:
    description: This command will set the player rank.
    usage: 'Run /setrank with no arguments to see a full help'
    permission: jawapermissions.setrank
  ban:
    description: Will ban a player
    usage: 'Run /ban with no arguments to see a full help'
    permission: jawapermissions.ban
  unban:
    description: Will unban a player.
    usage: 'Run /unban with no arguments to see a full help'
    permission: jawapermissions.unban
  testcommand:
    permission: jawapermissions.testcommand
  reloadperms:
    description: Reloads the permissions from disk and recaches them.
    permission: jawapermissions.reload
  who:
    description: Gives relavant user data.
    permission: jawapermissions.who
  baninfo:
    description: "Gives a user information about another's ban"
    permission: jawapermissions.baninfo
  alt:
    description: "Gives staff information about possible account alternets"
    usage: "/alt <player>"
    permission: jawapermissions.alt
  playerinfo:
    description: "Gives staff detailed player info"
    permission: jawapermissions.playerinfo
  rankinfo:
    description: "Provides information about a rank"
    usage: "/rankinfo [description|requirements] <rank>"
    permission: jawapermissions.rankinfo
  playercomment:
    description: "Allows the viewing, addition, and removal of comments from a player's data"
    usage: "/playercomment <player> [add|remove|list] [<comment>|<comment#>|<page #>]"
    permission: jawapermissions.playercomment
    
permissions:
  jawapermissions.alt:
    description: "Allows searching for alt accounts based on IP address"
    default: op
  jawapermissions.baninfo:
    description: "Allows viewing of ban data"
    default: op
  jawapermissions.who:
    description: "Allows a user to see who is online"
    default: true
  jawapermissions.who.detail:
    description: "Allows an administrative user to see detailed information about a player"
    default: op
  jawapermissions.reload:
    description: "Allows an administrative user to reload rank permissions, immunity levels, rank descriptions, and colors"
    default: op
  jawapermissions.ban:
    description: "Allows an administrative user to ban a user"
    default: op
  jawapermissions.unban:
    description: "Allows an administative user to unban a user"
    default: op
  jawapermissions.setrank:
    description: "Allows an administative user to set the rank of a user"
    default: op
  jawapermissions.uuid:
    description: "Allows an administative user to see the UUID of a player"
    default: op
  jawapermissions.rankinfo:
    description: "Allows a player to see the description or requirements for a rank"
    deafult: true
  jawapermissions.playercomment:
    description: "Allows an administrative user to see admin comments on a user"
    default: false
  jawapermissions.playercomment.add:
    description: "Allows an administrative user to add admin comments on a user"
    default: false
  jawapermissions.playercomment.remove:
    description: "Allows an administrative user to remove admin comments on a user"
    default: false